### PR TITLE
scTour: avoid 'SparseCSRView' object has no attribute 'A' error.

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by GWMcElfresh** [comment]
Everything looks fine under:  
```
OS: Windows 11
python: 3.9
scanpy: 1.10.2
pandas: 2.03
```
I'm having it print some more package versions to see if I can repro the failure.

**Comment by GWMcElfresh** [comment]
networkx == 3.3 rules out Python 3.9. It's not immediately obvious what version of python docker-base pulls from apt, so I'm just having it print the version.

**Comment by GWMcElfresh** [comment]
OK, I can repro under

``` 
OS: WIndows 11
python: 3.10.11 (docker-base uses 3.10.12, but no binary for windows)
scanpy: 1.10.2
pandas: 2.2.2
numpy: 1.26.4
scipy: 1.14.0
networkx: 3.3
```
relevant depreciation post here: https://stackoverflow.com/questions/26576524/how-do-i-transform-a-scipy-sparse-matrix-to-a-numpy-matrix

scipy 1.14 did away with `.A` == `.toarray()`, which throws the error. 

I'm checking to see if we can dodge a check within sctour. Alternatively, we could just use `scipy <= 1.13`.

**Comment by bbimber** [comment]
@GWMcElfresh, if that's the issue, should we ask scTour about changing this: https://github.com/LiQian-XC/sctour/blob/86e21fe356012776d55a07f7c2fa7013dc19def8/sctour/data.py#L99

**Comment by GWMcElfresh** [comment]
That last commit seems to fix scTour's issue. The remaining test failure is https://github.com/bimberlabinternal/CellMembrane/blob/d6800907749fc1182cc614c2379b242e225eda9e/tests/testthat/test-seurat.R#L100

Just something unexpected with pairwise Find Markers?

**Comment by bbimber** [comment]
It's possible that test was never passing, and masked by scTour. Can you update that check to expect 2224, and let's see if these pass now?

**Comment by GWMcElfresh** [comment]
> 2224

ah got it - yeah it looks like the expectation is pulled from a non-pairwise find markers call, which I would expect to give fewer DEGs.

**Pull request merged**
