### PR TITLE
Update gene model (with automation) 

### PR DESCRIPTION
**Pull request by GWMcElfresh**
Hi all, 

I added an automatic LOC gene annotation from Entrez/NCBI and Ensembl gene mappings (joined by common Ensembl ID). 

This automatically replaces 1385 LOC genes. 353 of these genes are non-conclusive (e.g. if the HGNC name for a protein is MYO1 and the external_gene_name name is MYO2, the gene mapping is non-conclusive). In this case, the common prefix MYO is accepted and an ambiguity suffix is added, yielding MYO.PERHAPS to make sure it doesn't get pulled in unintentionally during GSEA/etc. If there is no common prefix, the LOC name is reinstated. 

We can discuss if we want to drop the HGNC inclusion - seems like a good idea for now to add a small amount of homology enforcement to an otherwise completely unsupervised annotation. 

I'm currently forcing this to occur after any manual annotation, as T cell receptor/IG genes are automatically replaced. I think I'll end up manually annotating those as I find them.

### CODE REVIEW

**Review by bbimber — CHANGES_REQUESTED** [review]
@GWMcElfresh See the commits i made to fix dependencies. Overall this is probably good, but a few comments:

- .UpdateGeneModel performs a non-trivial amount of work now, since it's downloading the ensembl data. As-is, UpdateMacaqueMmul10NcbiGeneSymbols() calls that function a bunch of times. Instead, we should call it once, making a map of oldname -> new name. We should then take this map and replace the gene names in all the right places in the seurat object. 
- I'd actually propose you split this into three functions: .UpdateGeneModel, which takes the list of features and returns the renamed ones. Next, have a .ReplaceFeaturesInSeurat function, which takes a list of features and replaces them in all the right places in the seurat object. Finally, UpdateMacaqueMmul10NcbiGeneSymbols, which uses both of these to make the changes.
- This should get simple testing. See test-data.R, and the test for RenameUsingCD to give a simple example of how you might do this.

**Comment by bbimber** [comment]
One additional thing. These should really have some test cases. I suggest making a new "test-aliasing.R' (or whatever name) file. You can see test-data.R for simple examples that are similar to what I'd expect to see for something like this. for example:
```
test_that("CD genes translation works", {
	expect_equal(RenameUsingCD(c('ITGB1', 'EGLN3', 'Other', 'CD52')), c('ITGB1 (CD29)', 'EGLN3', 'Other', 'CD52 (CDW52)'))
})
```

You could imagine some simple examples like this here. The most important methods could probably be exercised with simple inputs like the above. There are examples in the tests here about mocking up seurat objects, which is something you might need here. We also have a seurat RDS in this project, which might actually be useful if you want to have a working object with reductions to test the full rename process.

**Comment by bbimber** [comment]
@GWMcElfresh do you think this will ever go anywhere?

**Comment by GWMcElfresh** [comment]
With `ResolveLocGenes()`, I think this is probably redundant.  I think we've landed on dealing with LOC genes either by adding them to exclusion lists or post-hoc with `ResolveLocGenes()`, so I'm okay with closing.

**Pull request closed without merging**
