### PR TITLE
add "AddNewMetaColumn" function

### PR DESCRIPTION
**Pull request by gboggy2**
Hi all,

I’ve created this new function to enable dynamic creation of a new Seurat object metadata column from current metadata columns by using formulas to apply new labels. I envision using this within prime-seq to create a new metadata column, as part of a pipeline, which can then be used for splitting and reprocessing (rather than downloading the object, creating the new metadata column, and uploading the updated Seurat object to prime-seq for splitting and processing).

### CODE REVIEW

**Comment by bbimber** [comment]
@gboggy2: interesting idea. Can you please add a handful of small test cases, adding to here: https://github.com/bimberlabinternal/CellMembrane/blob/master/tests/testthat/test-utils.R

You'll see that it loads a specific seurat object packaged with this module. I would use your function to create a column or two, and then table() the values of the column and use expect_equal to ensure they match what you expect

**Comment by bbimber** [comment]
@gboggy2, you'll also need to run devools::document() to update the roxygen docs

**Comment by GWMcElfresh** [comment]
you may want to sanity check the new metadata column too after you create it. if this is going to be on prime-seq, it would kind of suck to run it (with a typo in the formula) and then need to resubmit the job since you can't easily roll back the step. 

I think one way you could do this is by a default variable `allowNAs = FALSE` then at the end, after computing your new metadata column, you just check `any(is.na(seuratObj@meta.data[,varname]))` and error if true. 

this is a weak check if you intend to leave NAs (like your example here: `c(Tcell_NaiveToEffector > 10 ~ "Effector", Tcell_NaiveToEffector < 5 ~ "Naive")`), but I think I would generally try to define everything.

**Comment by GWMcElfresh** [comment]
I missed the defaultname parameter on my first read through, so NAs aren't an issue. I added a sanity check that ensures that all of the formula results need to show up in the new metadata or the code will error (with test). 

@gboggy2 do you know if the "handedness" of the formula are always going to be the same? Namely, is `nCount_RNA > 2000 ~ "High"` parsed equivalently to `"High" ~ nCount_RNA > 2000` or will it always apply as "look for the condition on the right of the tilde, then assign what is on the left of the tilde"?

**Comment by gboggy2** [comment]
> I missed the defaultname parameter on my first read through, so NAs aren't an issue. I added a sanity check that ensures that all of the formula results need to show up in the new metadata or the code will error (with test).
> 
> @gboggy2 do you know if the "handedness" of the formula are always going to be the same? Namely, is `nCount_RNA > 2000 ~ "High"` parsed equivalently to `"High" ~ nCount_RNA > 2000` or will it always apply as "look for the condition on the left of the tilde, then assign what is on the right of the tilde"?

@GWMcElfresh according to https://www.sharpsightlabs.com/blog/case-when-r/ the label is always on the right.

**Pull request merged**
